
[env]
TERM = "xterm-256color"

[font]
size = 8.5

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[[hints.enabled]]
command = "xdg-open"
hyperlinks = true
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.binding]
key = "U"
mods = "Control|Shift"

[hints.enabled.mouse]
enabled = true
mods = "None"

[[keyboard.bindings]]
chars = "\u0002\""
key = "V"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0002%"
key = "S"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0002c"
key = "N"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0002p"
key = "H"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0002n"
key = "L"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0002&"
key = "W"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0002R"
key = "R"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0002("
key = "J"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0002)"
key = "K"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0002z"
key = "Z"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0002!"
key = "Q"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0002\u001B[A"
key = "Up"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0002\u001B[B"
key = "Down"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0002\u001B[D"
key = "Left"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0002\u001B[C"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0002\u001B[1;5A"
key = "Up"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u0002\u001B[1;5B"
key = "Down"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u0002\u001B[1;5D"
key = "Left"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u0002\u001B[1;5C"
key = "Right"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u0002\u001B[D"
key = "H"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u0002\u001B[C"
key = "L"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u0002\u001B[A"
key = "J"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u0002\u001B[B"
key = "K"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u0002;"
key = "Z"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u0002x"
key = "Q"
mods = "Alt|Shift"

[mouse]
hide_when_typing = true

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[scrolling]
history = 10000
multiplier = 1

[selection]
save_to_clipboard = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[window]
opacity = 1

[general]
import = ["/home/hans/.config/alacritty/rose-pine.toml"]
